"""Add lottery previews

Revision ID: 5e8b4a543cb6
Revises: 825f5e6e99a5
Create Date: 2025-11-27 16:49:05.820484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8b4a543cb6'
down_revision = '825f5e6e99a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('preview_big', sa.String(length=500), nullable=True))
    op.add_column('lotteries', sa.Column('preview_small', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'preview_small')
    op.drop_column('lotteries', 'preview_big')
    # ### end Alembic commands ###
