"""add_lottery_and_tickets

Revision ID: 66f43dfd8caa
Revises: cf286553fc52
Create Date: 2025-09-15 15:36:44.269473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f43dfd8caa'
down_revision = 'cf286553fc52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.Integer(), dimensions=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('lotteries')
    # ### end Alembic commands ###
