"""Add lottery name

Revision ID: 6910ce2a167f
Revises: bf1549393529
Create Date: 2025-11-16 15:56:55.218220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6910ce2a167f'
down_revision = 'bf1549393529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('name', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'name')
    # ### end Alembic commands ###
