"""Add tickets status and lottery task_id

Revision ID: 825f5e6e99a5
Revises: eac744b80d3b
Create Date: 2025-11-24 19:03:55.732445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '825f5e6e99a5'
down_revision = 'eac744b80d3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM('NOT_PLAYED', 'LOSE', 'WIN', name='ticketstatus', create_type=False)
    status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('lotteries', sa.Column('task_id', sa.String(length=32), nullable=True))
    op.add_column('tickets', sa.Column('status', status_enum, nullable=False, server_default='NOT_PLAYED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    op.drop_column('lotteries', 'task_id')
    # ### end Alembic commands ###
