"""Add lottery type

Revision ID: a90c8a98ed83
Revises: 5e8b4a543cb6
Create Date: 2025-11-27 17:51:08.630658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a90c8a98ed83'
down_revision = '5e8b4a543cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    type_enum = postgresql.ENUM('BIG', 'SMALL', name='lotterytype', create_type=False)
    type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('lotteries', sa.Column('lottery_type', type_enum, server_default='SMALL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'lottery_type')
    # ### end Alembic commands ###
