"""add_ended_at_field


Revision ID: bf1549393529
Revises: 66f43dfd8caa
Create Date: 2025-09-21 18:24:35.765063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1549393529'
down_revision = '66f43dfd8caa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('ended_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'ended_at')
    # ### end Alembic commands ###
