version: '3'

networks:
  lottery_network:
    driver: bridge

services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: lottery_db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - lottery-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lottery_network

  backend:
    container_name: lottery-backend
    image: lottery-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lottery_network

  frontend:
    container_name: lottery-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - lottery_network

  nginx:
    image: nginx:1.29-alpine
    container_name: lottery_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    ports:
      - 1337:80
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - backend
      - frontend
    networks:
      - lottery_network
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - lottery_network

  redis:
    image: redis:latest
    container_name: lottery_redis
    hostname: ${REDIS_HOST}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lottery_network

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: lottery-pgadmin
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - lottery-database:/var/lib/postgresql/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lottery_network

volumes:
  shared-storage:
  rabbitmq-data:
  lottery-database:
     external: true
