version: '3'

services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: lottery_db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - lottery-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    user: postgres

  backend:
    container_name: lottery-backend
    image: lottery-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
     - db

  frontend:
    container_name: lottery-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.29-alpine
    container_name: lottery_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    ports:
      - 1337:80
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - backend
      - frontend
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  shared-storage:
  rabbitmq-data:
  lottery-database:
     external: true

