name: Linting

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/prod.txt
        pip install -r backend/requirements/dev.txt
    - name: Lint with flake8
      working-directory: ./backend
      run: flake8 .
    - name: Check with ruff
      working-directory: ./backend
      run: ruff check .
