name: ESLint

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run ESLint
      working-directory: ./frontend
      run: npx eslint .
